version: '3'

services:
  ibilis_web_app:
    image: node:18
    volumes:
      - ./MLabDocker:/MLabDocker
    working_dir: /MLabDocker/MLAB-Core-Release/server
    command: ["node", "index.mjs"]
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
      - mynetwork

  Iblis_docs:
    image: nginx:latest
    volumes:
      - ./MLabDocker/MLAB-Core-Release/vite:/usr/share/nginx/html
    ports:
      - "4173:80"
    networks:
      - mynetwork

  Iblis_reception:
    image: nginx:latest
    volumes:
      - ./MLabDocker/MLAB-Core-Release/iblis_reception:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "8002:80"
    networks:
      - mynetwork
  
  mysql8:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    restart: always
    networks:
      - mynetwork
  
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - mynetwork

  test_API:
    image: ruby:3.2.0
    volumes:
      - ./MLabDocker/mlab_api:/app
      - ./cupsd.conf:/etc/cups/cupsd.conf
    command: >
      bash -c "
      apt-get update && apt-get install -y default-mysql-client cups &&
      service cups stop && service cups start &&
      cd app && gem install bundler && bundle install && rails s -b 0.0.0.0 -p 3000"
    ports:
      - "8005:3000"
      - "632:631"
    depends_on:
      - mysql8
      - redis
      - elasticsearch
    networks:
      - mynetwork
  
  # cups:
  #   image: anujdatar/cups
  #   container_name: cups
  #   restart: unless-stopped
  #   ports:
  #       - "633:631"
  #   devices:
  #       - /dev/bus/usb:/dev/bus/usb
  #   environment:
  #       - CUPSADMIN=batman
  #       - CUPSPASSWORD=batcave_password
  #       - TZ="America/Gotham"
  #   # volumes:
  #   #     - <persistent-config-path>:/etc/cups
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    external: true

# rm /app/tmp/pids/server.pid &&
