version: '3'

services:
  ibilis_web_app:
    image: node:18
    volumes:
      - ./MLabDocker:/MLabDocker
    working_dir: /MLabDocker/MLAB-Core-Release/server
    command: ["node", "index.mjs"]
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
      - mynetwork

  Iblis_docs:
    image: nginx:latest
    volumes:
      - ./MLabDocker/MLAB-Core-Release/vite:/usr/share/nginx/html
    ports:
      - "4173:80"
    networks:
      - mynetwork

  Iblis_reception:
    image: nginx:latest
    volumes:
      - ./MLabDocker/MLAB-Core-Release/iblis_reception:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8002:80"
    networks:
      - mynetwork
  
  mysql8:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    restart: always
    networks:
      - mynetwork
  
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mynetwork

  mlab_api:
    build:
      context: ./MLabDocker/mlab_api
      dockerfile: Dockerfile
    ports:
      - "8005:3000"
    networks:
      - mynetwork
    depends_on:
      - mysql8
      - redis

networks:
  mynetwork:
    external: true
