version: '3'

services:
  ibilis_web_app:
    image: node:18
    volumes:
      - ./MLabDocker:/MLabDocker
    working_dir: /MLabDocker/MLAB-Core-Release/server
    command: ["node", "index.mjs"]
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
      - mynetwork

  Iblis_docs:
    image: nginx:latest
    volumes:
      - ./MLabDocker/MLAB-Core-Release/vite:/usr/share/nginx/html
    ports:
      - "4173:80"
    networks:
      - mynetwork

  Iblis_reception:
    image: nginx:latest
    volumes:
      - ./MLabDocker/MLAB-Core-Release/iblis_reception:/usr/share/nginx/html
    ports:
      - "8002:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
