version: '3'

services:
  node-app:
    image: node:18
    volumes:
      - ./MLabDocker:/MLabDocker
    working_dir: /MLabDocker/MLAB-Core-Release/server
    command: ["node", "index.mjs"]
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
